import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Todo App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  text-gray-700  h-screen`}>
      <Toaster position="top-center" reverseOrder={false} />
      {children}</body>
    </html>
  )
}


// bg-gradient-to-b from-white via-[#7360DF] to-[#33186B]